# TODO: This needs to be discussed before integration. Need to document the performance and HA tradeoffs.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # It is absolutely critical that DS instances use "local"
  # persistent volumes for their databases and changelogs.
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
