apiVersion: v1
kind: ConfigMap
metadata:
  name: boot-json
data:
  boot.json: |
    {
      "instance" : "http://openam:80/am",
      "dsameUser" : "cn=dsameuser,ou=DSAME Users,ou=am-config",
      "keystores" : {
        "default" : {
          "keyStorePasswordFile" : "/var/run/secrets/am/boot/.storepass",
          "keyPasswordFile" : "/var/run/secrets/am/boot/.keypass",
          "keyStoreType" : "JCEKS",
          "keyStoreFile" : "/var/run/secrets/am/boot/keystore.jceks"
        }
      },
      "configStoreList" : [ {
        "baseDN" : "ou=am-config",
        "dirManagerDN" : "uid=am-config,ou=admins,ou=am-config",
        "ldapHost" : "ds-idrepo",
        "ldapPort" : 1389,
        "ldapProtocol" : "ldap"
      } ]
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: am
data:
  CATALINA_OPTS: >
    -server
    -Xmx1g
    -Dcom.iplanet.services.stats.state=off
    -D
