apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: am
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: openam
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 2000m
            memory: 4Gi