apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: idm
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: openidm
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 1500m
            memory: 2Gi