kind: ""
apiversion: ""
# Experimental - grabs the namespace from a deployed object
# Making it available for use in templates.
vars:
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: Secret
    name: platform-secrets
  fieldref:
    fieldpath: metadata.namespace
resources:
- platform-config.yaml
- platform-secrets.yaml
configurations:
- var.yaml

